// Code generated by protoc-gen-go.
// source: CollectorMessageRQ.proto
// DO NOT EDIT!

/*
Package collector is a generated protocol buffer package.

It is generated from these files:
	CollectorMessageRQ.proto
	CollectorMessageRS.proto

It has these top-level messages:
	Value
	Pulse
	PulsesRQ
	PulsesRS
*/
package collector

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Value struct {
	Name             *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Values           []string `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}

func (m *Value) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Value) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type Pulse struct {
	TypeId           *string  `protobuf:"bytes,1,req,name=typeId" json:"typeId,omitempty"`
	InstanceId       *string  `protobuf:"bytes,2,req,name=instanceId" json:"instanceId,omitempty"`
	Time             *int64   `protobuf:"varint,3,req,name=time" json:"time,omitempty"`
	Values           []*Value `protobuf:"bytes,4,rep,name=values" json:"values,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Pulse) Reset()         { *m = Pulse{} }
func (m *Pulse) String() string { return proto.CompactTextString(m) }
func (*Pulse) ProtoMessage()    {}

func (m *Pulse) GetTypeId() string {
	if m != nil && m.TypeId != nil {
		return *m.TypeId
	}
	return ""
}

func (m *Pulse) GetInstanceId() string {
	if m != nil && m.InstanceId != nil {
		return *m.InstanceId
	}
	return ""
}

func (m *Pulse) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Pulse) GetValues() []*Value {
	if m != nil {
		return m.Values
	}
	return nil
}

type PulsesRQ struct {
	Version          *string  `protobuf:"bytes,1,req,name=version" json:"version,omitempty"`
	Pulse            []*Pulse `protobuf:"bytes,2,rep,name=pulse" json:"pulse,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PulsesRQ) Reset()         { *m = PulsesRQ{} }
func (m *PulsesRQ) String() string { return proto.CompactTextString(m) }
func (*PulsesRQ) ProtoMessage()    {}

func (m *PulsesRQ) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *PulsesRQ) GetPulse() []*Pulse {
	if m != nil {
		return m.Pulse
	}
	return nil
}
